export type ArtworkType = {
  objectID: number;
  title: string;
  primaryImage: string;
  accessionYear: string;
  department: string;
  culture: string;
  objectDate: string;
  GalleryNumber: string;
  geographyType: string;
  country: string;
  medium: string;
  dimensions: string;
  creditLine: string;
  accessionNumber: string;  
  // primaryImageSmall: string;
  // additionalImages: string[];  
  // objectName: string;  
  // period: string;
  // dynasty: string;
  // reign: string;
  // portfolio: string;
  // artistRole: string;
  // artistPrefix: string;
  // artistDisplayName: string;
  // artistDisplayBio: string;
  // artistSuffix: string;
  // artistAlphaSort: string;
  // artistNationality: string;
  // artistBeginDate: string;
  // artistEndDate: string;
  // artistGender: string;
  // artistWikidata_URL: string;
  // objectBeginDate: number;
  // objectEndDate: number;
  // city: string;
  // state: string;
  // county: string;
  // region: string;
  // subregion: string;
  // locale: string;
  // locus: string;
  // excavation: string;
  // river: string;
  // classification: string;
  // rightsAndReproduction: string;
  // linkResource: string;
  // metadataDate: string;
  // repository: string;
  // objectURL: string;
  // objectWikidata_URL: string;
  // isTimelineWork: boolean;
  // relation: string;
  // isHighlight: boolean;
  // isPublicDomain: boolean;
};
